DELETE FROM media_items;
INSERT INTO media_items (title, media_type, src, description, sort_order, is_published) VALUES
('09.05MONTACARGUIStASMA','video','/img/09.05MONTACARGUIStASMA.mp4',NULL,1,1),
('BecariosprogramacióN','image','/img/becariosprogramacio%CC%81n.png',NULL,2,1),
('BENEFICIOSDESEISHIN','image','/img/BENEFICIOSDESEISHIN.png',NULL,3,1),
('BlackandBeigePhotoNewPostInstagramPost','image','/img/BlackandBeigePhotoNewPostInstagramPost.png',NULL,4,1),
('BlackandYellowModernHeavyEquipmentRentalInstagramPost','image','/img/BlackandYellowModernHeavyEquipmentRentalInstagramPost.png',NULL,5,1),
('BlackandYellowModernHeavyEquipmentRentalsInstagramPost','image','/img/BlackandYellowModernHeavyEquipmentRentalsInstagramPost.png',NULL,6,1),
('BlueandYellowModernInternshipProgramInstagramPost','image','/img/BlueandYellowModernInternshipProgramInstagramPost.png',NULL,7,1),
('CarrouseldefotosSeishinsgs 1','image','/img/CarrouseldefotosSeishinsgs-1.png',NULL,8,1),
('CarrouseldefotosSeishinsgs 2','image','/img/CarrouseldefotosSeishinsgs-2.png',NULL,9,1),
('CarrouseldefotosSeishinsgs 3','image','/img/CarrouseldefotosSeishinsgs-3.png',NULL,10,1),
('CarrouseldefotosSeishinsgs 4','image','/img/CarrouseldefotosSeishinsgs-4.png',NULL,11,1),
('CarrouseldefotosSeishinsgs 5','image','/img/CarrouseldefotosSeishinsgs-5.png',NULL,12,1),
('CarrouseldefotosSeishinsgs 6','image','/img/CarrouseldefotosSeishinsgs-6.png',NULL,13,1),
('Carruseldeconsejospara ENTRVISTALABORAÑ 1','image','/img/Carruseldeconsejospara%20ENTRVISTALABORAN%CC%83-1.png',NULL,14,1),
('Carruseldeconsejospara ENTRVISTALABORAÑ 2','image','/img/Carruseldeconsejospara%20ENTRVISTALABORAN%CC%83-2.png',NULL,15,1),
('Carruseldeconsejospara ENTRVISTALABORAÑ 3','image','/img/Carruseldeconsejospara%20ENTRVISTALABORAN%CC%83-3.png',NULL,16,1),
('CarruseldeconsejosparaENTRVISTALABORAN 4','image','/img/CarruseldeconsejosparaENTRVISTALABORAN-4.png',NULL,17,1),
('CarruseldeconsejosparaENTRVISTALABORAÑ 5','image','/img/CarruseldeconsejosparaENTRVISTALABORAN%CC%83-5.png',NULL,18,1),
('CONTRATACIONINSPECTORES','image','/img/CONTRATACIONINSPECTORES.png',NULL,19,1),
('Cuadrocomparativo','image','/img/Cuadrocomparativo.png',NULL,20,1),
('CUENTANOSPOST','image','/img/CUENTANOSPOST.png',NULL,21,1),
('Flyerinspectordecalidad23','image','/img/flyerinspectordecalidad23.png',NULL,22,1),
('FLYMONTACARGUISTA','image','/img/FLYMONTACARGUISTA.png',NULL,23,1),
('FraseFelizJulioNuevoMesMinimalistaRosa','video','/img/FraseFelizJulioNuevoMesMinimalistaRosa.mp4',NULL,24,1),
('GreenandGraySimpleCleanHowToTipsCarouselInstagramPost 1','image','/img/GreenandGraySimpleCleanHowToTipsCarouselInstagramPost-1.png',NULL,25,1),
('GreenandGraySimpleCleanHowToTipsCarouselInstagramPost 2','image','/img/GreenandGraySimpleCleanHowToTipsCarouselInstagramPost-2.png',NULL,26,1),
('GreenandGraySimpleCleanHowToTipsCarouselInstagramPost 3','image','/img/GreenandGraySimpleCleanHowToTipsCarouselInstagramPost-3.png',NULL,27,1),
('GreenandGraySimpleCleanHowToTipsCarouselInstagramPost 4','image','/img/GreenandGraySimpleCleanHowToTipsCarouselInstagramPost-4.png',NULL,28,1),
('HistoriaparaInstagramHolaLunesModernoRosa','image','/img/HistoriaparaInstagramHolaLunesModernoRosa.png',NULL,29,1),
('Historiaparainstagraminvitacioneventoferiadecomidabeigeynaranja','video','/img/Historiaparainstagraminvitacioneventoferiadecomidabeigeynaranja.mp4',NULL,30,1),
('IndependenciadeMéXicoModernoVerde','video','/img/IndependenciadeMe%CC%81xicoModernoVerde.mp4',NULL,31,1),
('INSPECTORDECAALIDAD020(1)','image','/img/INSPECTORDECAALIDAD020(1).png',NULL,32,1),
('INSPECTORDECAALIDAD0207','image','/img/INSPECTORDECAALIDAD0207.png',NULL,33,1),
('INTERACTIVO1','image','/img/INTERACTIVO1.png',NULL,34,1),
('Interactivo2','image','/img/interactivo2.png',NULL,35,1),
('MisióNdehoy','video','/img/Misio%CC%81ndehoy.mp4',NULL,36,1),
('MONTACARGUISTA','image','/img/MONTACARGUISTA.png',NULL,37,1),
('MONTACARGUISTAPROMA22 9','image','/img/MONTACARGUISTAPROMA22-9.png',NULL,38,1),
('PostdeInstagramdíAdemuertoscoloridomorado','image','/img/PostdeInstagramdi%CC%81ademuertoscoloridomorado.png',NULL,39,1),
('Postdeinstagraminscripcionesacademiabaloncestotexturizadoazul','image','/img/Postdeinstagraminscripcionesacademiabaloncestotexturizadoazul.png',NULL,40,1),
('POSTFLYERINSPECTOR2205(PostparaFacebook) 1','image','/img/POSTFLYERINSPECTOR2205(PostparaFacebook)-1.png',NULL,41,1),
('POSTFLYERINSPECTOR2205(PostparaFacebook) 2','image','/img/POSTFLYERINSPECTOR2205(PostparaFacebook)-2.png',NULL,42,1),
('PostinstagramdiadeReyesMagosilustradoazulydorado','image','/img/PostinstagramdiadeReyesMagosilustradoazulydorado.png',NULL,43,1),
('PostInstagramFelizAñONuevoGlobos3DDorado','image','/img/PostInstagramFelizAn%CC%83oNuevoGlobos3DDorado.png',NULL,44,1),
('PostparaFacebookFelizDíAdelPadreModernoAzul','image','/img/PostparaFacebookFelizDi%CC%81adelPadreModernoAzul.png',NULL,45,1),
('PostparaInstagramFelizAñO2026simpleAzulyDorado','image','/img/PostparaInstagramFelizAn%CC%83o2026simpleAzulyDorado.png',NULL,46,1),
('Redandcreamcollagecontentmarketinginstagramcarousel 1','image','/img/Redandcreamcollagecontentmarketinginstagramcarousel-1.png',NULL,47,1),
('Redandcreamcollagecontentmarketinginstagramcarousel 2','image','/img/Redandcreamcollagecontentmarketinginstagramcarousel-2.png',NULL,48,1),
('Redandcreamcollagecontentmarketinginstagramcarousel 3','image','/img/Redandcreamcollagecontentmarketinginstagramcarousel-3.png',NULL,49,1),
('Redandcreamcollagecontentmarketinginstagramcarousel 4','image','/img/Redandcreamcollagecontentmarketinginstagramcarousel-4.png',NULL,50,1),
('RedandWhiteModernChristmasPartyInvitation','image','/img/RedandWhiteModernChristmasPartyInvitation.png',NULL,51,1),
('RedBlackandWhiteModernCarRentalInstagramPost','image','/img/RedBlackandWhiteModernCarRentalInstagramPost.png',NULL,52,1),
('ReelmontacarguistasanmiguelPostparaFacebook','video','/img/ReelmontacarguistasanmiguelPostparaFacebook.mp4',NULL,53,1),
('REELSABESQUEHACEUNINSPECTORDECALIDAD','video','/img/REELSABESQUEHACEUNINSPECTORDECALIDAD.mp4',NULL,54,1),
('SEISHININSPECTOR','image','/img/SEISHININSPECTOR.png',NULL,55,1),
('Testimoniostoruy','image','/img/Testimoniostoruy.png',NULL,56,1),
('Vacantechofer','image','/img/vacantechofer.png',NULL,57,1),
('VACANTETRADUCTOR','image','/img/VACANTETRADUCTOR.png',NULL,58,1),
('WhiteRedAndToscaModernWeAreHiringInstagramPost','image','/img/WhiteRedAndToscaModernWeAreHiringInstagramPost.png',NULL,59,1)
;
